<?php
	$kontak_pj = db_get_all_data('user_kontak', ['user_id' => $posko->posko_penanggung_jawab]);

	$pj = [];
	foreach ($kontak_pj as $item) {
		$nokon[] = $item->user_kontak_name;
	}

	$kontak_penannggung_jawab = implode(', ', $nokon);

	$kontak_pic = db_get_all_data('user_kontak', ['user_id' => $posko->posko_pic]);

	$pic = [];
	foreach ($kontak_pic as $item) {
		$pic[] = $item->user_kontak_name;
	}

	$kontak_pc = implode(', ', $pic);
?>

<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
	//This page is a result of an autogenerated content made by running test.html with firefox.
	function domo() {
		// Binding keys
		$('*').bind('keydown', 'Ctrl+e', function assets() {
			$('#btn_edit').trigger('click');
			return false;
		});

		$('*').bind('keydown', 'Ctrl+x', function assets() {
			$('#btn_back').trigger('click');
			return false;
		});
	}

	jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Posko <small><?= cclang('detail', ['Posko']); ?> </small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class=""><a href="<?= site_url('administrator/posko'); ?>">Posko</a></li>
		<li class="active"><?= cclang('detail'); ?></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body ">
					<!-- Widget: user widget style 1 -->
					<div class="box box-widget widget-user-2">
						<!-- Add the bg color to the header using any of the bg-* classes -->
						<div class="widget-user-header">
							<div class="widget-user-image">
								<img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
							</div>
							<!-- /.widget-user-image -->
							<h3 class="widget-user-username">Posko</h3>
							<h5 class="widget-user-desc">Detail Posko</h5>
							<hr>
						</div>

						<div class="form-horizontal form-step" name="form_posko" id="form_posko">

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">ID </label>

								<div class="col-sm-8">
									<span class="detail_group-posko_id"><?= _ent($posko->posko_id); ?></span>
								</div>
							</div>

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">Kecamatan </label>

								<div class="col-sm-8">
									<?= _ent($posko->kecamatan_nama); ?>
								</div>
							</div>

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">Kelurahan </label>

								<div class="col-sm-8">
									<?= _ent($posko->kelurahan_nama); ?>
								</div>
							</div>

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">Nama Posko</label>

								<div class="col-sm-8">
									<span class="detail_group-posko-nama"><?= _ent($posko->posko_nama); ?></span>
								</div>
							</div>

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">Penanggung Jawab Posko </label>

								<div class="col-sm-8">
									<?= _ent($posko->nama_lengkap_penanggung_jawab); ?>
								</div>
							</div>

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">Kontak Penanggung Jawab Posko </label>

								<div class="col-sm-8"><?= $kontak_penannggung_jawab;?></div>
							</div>

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">PIC Posko </label>

								<div class="col-sm-8">
									<?= _ent($posko->nama_lengkap_pic); ?>
								</div>
							</div>

							<div class="form-group ">
								<label for="content" class="col-sm-2 control-label">Kontak PIC Posko </label>

								<div class="col-sm-8"><?= $kontak_pc;?></div>
							</div>

							<br>
							<br>




							<div class="view-nav">
								<?php is_allowed('posko_update', function() use ($posko){?>
								<a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back'
									title="edit posko (Ctrl+e)"
									href="<?= site_url('administrator/posko/edit/'.$posko->posko_id); ?>"><i
										class="fa fa-edit"></i> <?= cclang('update', ['Posko']); ?> </a>
								<?php }) ?>
								<a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)"
									href="<?= site_url('administrator/posko/'); ?>"><i class="fa fa-undo"></i>
									<?= cclang('go_list_button', ['Posko']); ?></a>
							</div>

						</div>
					</div>
				</div>
				<!--/box body -->
			</div>
			<!--/box -->

		</div>
	</div>
</section>
<!-- /.content -->

<script>
	$(document).ready(function () {
		(function () {
			var posko_nama = $('.detail_group-posko-nama');
		})()

	});
</script>