
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Jenis Layanan      <small><?= cclang('detail', ['Jenis Layanan']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/jenis_layanan'); ?>">Jenis Layanan</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Jenis Layanan</h3>
                     <h5 class="widget-user-desc">Detail Jenis Layanan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_jenis_layanan" id="form_jenis_layanan" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Layanan Id </label>

                        <div class="col-sm-8">
                        <span class="detail_group-jenis_layanan_id"><?= _ent($jenis_layanan->jenis_layanan_id); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Layanan </label>

                        <div class="col-sm-8">
                        <span class="detail_group-jenis_layanan_nama"><?= _ent($jenis_layanan->jenis_layanan_nama); ?></span>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('jenis_layanan_update', function() use ($jenis_layanan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit jenis_layanan (Ctrl+e)" href="<?= site_url('administrator/jenis_layanan/edit/'.$jenis_layanan->jenis_layanan_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Jenis Layanan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/jenis_layanan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Jenis Layanan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<script>
$(document).ready(function(){
   (function(){
        var jenis_layanan_nama = $('.detail_group-jenis_layanan_nama');
        var jenis_layanan_created_at = $('.detail_group-jenis_layanan_created_at');
        var jenis_layanan_user_created = $('.detail_group-jenis_layanan_user_created');
    })()
      
   });
</script>