
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Barangkeluar      <small><?= cclang('detail', ['Barangkeluar']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/barangkeluar'); ?>">Barangkeluar</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-primary">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Barangkeluar</h3>
                     <h5 class="widget-user-desc">Detail Barangkeluar</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_barangkeluar" id="form_barangkeluar" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID </label>

                        <div class="col-sm-8">
                        <span class="detail_group-id_barangkeluar"><?= _ent($barangkeluar->id_barangkeluar); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Penerima </label>

                        <div class="col-sm-8">
                           <?= _ent($barangkeluar->sumber_nama_sumber); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Barang </label>

                        <div class="col-sm-8">
                           <?= _ent($barangkeluar->barang_nama_barang); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Banyaknya </label>

                        <div class="col-sm-8">
                        <span class="detail_group-jumlah"><?= _ent($barangkeluar->jumlah); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Keterangan </label>

                        <div class="col-sm-8">
                        <span class="detail_group-keterangan"><?= _ent($barangkeluar->keterangan); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal </label>

                        <div class="col-sm-8">
                        <span class="detail_group-tanggal"><?= _ent($barangkeluar->tanggal); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Waktu </label>

                        <div class="col-sm-8">
                        <span class="detail_group-waktu"><?= _ent($barangkeluar->waktu); ?></span>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <!-- <?php is_allowed('barangkeluar_update', function() use ($barangkeluar){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit barangkeluar (Ctrl+e)" href="<?= site_url('administrator/barangkeluar/edit/'.$barangkeluar->id_barangkeluar); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Barangkeluar']); ?> </a>
                        <?php }) ?> -->
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/barangkeluar/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Barangkeluar']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<script>
$(document).ready(function(){
   (function(){
        var id_barang = $('.detail_group-id-barang');
        var tujuan = $('.detail_group-tujuan');
        var jumlah = $('.detail_group-jumlah');
    })()
      
   });
</script>