<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
	//This page is a result of an autogenerated content made by running test.html with firefox.
	function domo() {
		// Binding keys
		$('*').bind('keydown', 'Ctrl+e', function assets() {
			$('#btn_edit').trigger('click');
			return false;
		});

		$('*').bind('keydown', 'Ctrl+x', function assets() {
			$('#btn_back').trigger('click');
			return false;
		});
	}

	jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Barang Masuk <small><?= cclang('detail', ['Barang Masuk']); ?> </small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class=""><a href="<?= site_url('administrator/barangmasuk'); ?>">Barang Masuk</a></li>
		<li class="active"><?= cclang('detail'); ?></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body">
					<!-- Widget: user widget style 1 -->
					<div class="box box-widget widget-user-2">
						<!-- Add the bg color to the header using any of the bg-* classes -->
						<div class="widget-user-header ">
							<div class="widget-user-image">
								<img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
							</div>
							<!-- /.widget-user-image -->
							<h3 class="widget-user-username">Barang Masuk</h3>
							<h5 class="widget-user-desc">Detail Barang Masuk</h5>
							<hr>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="box box-primary">
									<div class="box-header"><h3 class="box-title">Detail Data Donatur</h3></div>
									<div class="box-body">
										<table class="table table-striped">
											<tr>
												<td>ID</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->id_barangmasuk);?></td>
											</tr>
											<tr>
												<td>Tanggal Donasi</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->tanggal);?></td>
											</tr>
											<tr>
												<td>Posko Donatur</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->posko_nama);?></td>
											</tr>
											<tr>
												<td>Nama Donatur</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->nama_donatur);?></td>
											</tr>
											<tr>
												<td>Alamat Donatur</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->alamat_donatur);?></td>
											</tr>
											<tr>
												<td>Kecamatan</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->kecamatan_nama);?></td>
											</tr>
											<tr>
												<td>Kelurahan</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->kelurahan_nama);?></td>
											</tr>
											<tr>
												<td>Nomor Telepon</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->kontak_donatur);?></td>
											</tr>
											<tr>
												<td>Keterangan</td>
												<td>:</td>
												<td><?= _ent($barangmasuk->keterangan);?></td>
											</tr>
										</table>
									</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="box box-primary">
									<div class="box-header"><h3 class="box-title">Detail Data Donasi Barang</h3></div>
									<div class="box-body">
										<table class="table table-striped">
											<tr>
												<th>No.</th>
												<th>Nama Barang</th>
												<th>Jumlah</th>
												<th>Keterangan</th>
											</tr>
									<?php
										$no = 1;
										foreach ($detailbarangmasuk as $item) {
									?>
											<tr>
												<td><?= $no++;?></td>
												<td><?= _ent($item->nama_barang);?></td>
												<td><?= _ent($item->jumlah).' '._ent($item->nama_satuan);?></td>
												<td><?= _ent($item->keterangan);?></td>
											</tr>
									<?php
										}
									?>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/box body -->
				<div class="box-footer">
					<?php is_allowed('barangmasuk_update', function() use ($barangmasuk){?>
					<a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit barangmasuk (Ctrl+e)" href="<?= site_url('administrator/barangmasuk/edit/'.$barangmasuk->id_barangmasuk); ?>">
						<i class="fa fa-edit"></i> <?= cclang('update', ['Barangmasuk']); ?>
					</a>
					<?php }) ?>
					<a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/barangmasuk/'); ?>">
						<i class="fa fa-undo"></i> <?= cclang('go_list_button', ['Barangmasuk']); ?>
					</a>
				</div>
			</div>
			<!--/box -->
		</div>
	</div>
</section>
<!-- /.content -->

<script>
	$(document).ready(function () {
		(function () {
			var asal = $('.detail_group-asal');
			var id_barang = $('.detail_group-id-barang');
			var jumlah = $('.detail_group-jumlah');
			var keterangan = $('.detail_group-keterangan');
		})()

	});
</script>