<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
	//This page is a result of an autogenerated content made by running test.html with firefox.
	function domo() {
		// Binding keys
		$('*').bind('keydown', 'Ctrl+e', function assets() {
			$('#btn_edit').trigger('click');
			return false;
		});

		$('*').bind('keydown', 'Ctrl+x', function assets() {
			$('#btn_back').trigger('click');
			return false;
		});
	}

	jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Permohonan <small><?= cclang('detail', ['Permohonan']); ?> </small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class=""><a href="<?= site_url('administrator/permohonan'); ?>">Permohonan</a></li>
		<li class="active"><?= cclang('detail'); ?></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body">
					<!-- Widget: user widget style 1 -->
					<div class="box box-widget widget-user-2">
						<!-- Add the bg color to the header using any of the bg-* classes -->
						<div class="widget-user-header">
							<div class="widget-user-image">
								<img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
							</div>
							<h3 class="widget-user-username">Permohonan</h3>
							<h5 class="widget-user-desc">Detail Permohonan</h5>
							<hr>
						</div>

						<div class="row">
							<div class="col-md-6">
								<div class="box box-primary">
									<div class="box-header"><h3 class="box-title">Detail Permohonan</h3></div>
									<div class="box-body">
										<table class="table table-striped table-responsive">
											<tr>
												<td>ID</td>
												<td>:</td>
												<td><?= _ent($permohonan->permohonan_id); ?></td>
											</tr>
											<tr>
												<td>Tanggal Permohonan</td>
												<td>:</td>
												<td><?= _ent($permohonan->permohonan_tanggal.' '.$permohonan->permohonan_waktu); ?></td>
											</tr>
											<tr>
												<td>Asal Posko</td>
												<td>:</td>
												<td><?= _ent($permohonan->posko_posko_nama); ?></td>
											</tr>
											<tr>
												<td>Pemohon</td>
												<td>:</td>
												<td><?= _ent($permohonan->permohonan_pemohon); ?></td>
											</tr>
											<tr>
												<td>Keterangan Pemohon</td>
												<td>:</td>
												<td><?= _ent($permohonan->permohonan_keterangan); ?></td>
											</tr>
											<tr>
												<td>Status</td>
												<td>:</td>
												<td>
											<?php
												if ($permohonan->permohonan_status == '1') {
													$status = '<label class="label label-danger">Belum diverifikasi</label>';
												} elseif ($permohonan->permohonan_status == '2') {
													$status = '<label class="label label-primary">Diverifikasi</label>';
												} elseif ($permohonan->permohonan_status == '3') {
													$status = '<label class="label label-warning">Diproses</label>';
												} elseif ($permohonan->permohonan_status == '4') {
													$status = '<label class="label label-info">Dikirim</label>';
												} elseif ($permohonan->permohonan_status == '5') {
													$status = '<label class="label label-success">Diterima</label>';
												} else {
													$status = '<i style="color: red; font-weight: bold;">Not Available</i>';
												}

												echo $status;
											?>
												</td>
											</tr>
											<tr>
												<td>Keterangan Posko</td>
												<td>:</td>
												<td><?= _ent($permohonan->permohonan_respon_posko); ?></td>
											</tr>
											<tr>
												<td>Mengetahui</td>
												<td>:</td>
												<td><?= _ent($permohonan->users_user_nama_lengkap); ?></td>
											</tr>
										</table>
									</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="box box-primary">
									<div class="box-header"><h3 class="box-title">Detail Permohonan</h3></div>
									<div class="box-body">
										<table class="table table-striped table-responsive">
											<thead>
												<tr>
													<th>No.</th>
													<th>Nama Barang</th>
													<th>Jumlah Barang</th>
													<th>Keterangan</th>
												</tr>
											</thead>
											<tbody>
										<?php
											$no = 1;
											foreach (db_get_all_data('permohonan_detail', ['permohonan_id' => $permohonan->permohonan_id]) as $item) {
										?>
											<tr>
												<td><?= $no++;?></td>
												<td><?= _ent(join_multi_select($item->barang_id, 'barang', 'id_barang', 'nama_barang'));?></td>
												<td><?= _ent($item->permohonan_detail_jumlah).' '._ent(join_multi_select(join_multi_select($item->barang_id, 'barang', 'id_barang', 'satuan'), 'satuan', 'id_satuan', 'nama_satuan'));?></td>
												<td><?= _ent($item->permohonan_detail_keterangan);?></td>
											</tr>
										<?php
											}
										?>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/box body -->
				<div class="box-footer">
				<?php
					if ($permohonan->permohonan_status == '1') {
						is_allowed('permohonan_update', function() use ($permohonan) {
				?>
					<a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit permohonan (Ctrl+e)" href="<?= site_url('administrator/permohonan/edit/'.$permohonan->permohonan_id); ?>">
						<i class="fa fa-edit"></i> <?= cclang('update', ['Permohonan']); ?> </a>
				<?php
					});
				}
				?>
					<a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/permohonan/'); ?>">
						<i class="fa fa-undo"></i> <?= cclang('go_list_button', ['Permohonan']); ?></a>
				</div>
			</div>
			<!--/box -->

		</div>
	</div>
</section>
<!-- /.content -->

<script>
	$(document).ready(function () {
		(function () {
			var permohonan_tanggal = $('.detail_group-permohonan-tanggal');
			var permohonan_waktu = $('.detail_group-permohonan-waktu');
			var posko_id = $('.detail_group-posko-id');
			var user_id = $('.detail_group-user-id');
			var permohonan_keterangan = $('.detail_group-permohonan-keterangan');
			var permohonan_status = $('.detail_group-permohonan-status');
			var permohonan_respon_posko = $('.detail_group-permohonan-respon-posko');
			var permohonan_mengetahui = $('.detail_group-permohonan-mengetahui');
		})()

	});
</script>