<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
	//This page is a result of an autogenerated content made by running test.html with firefox.
	function domo() {
		// Binding keys
		$('*').bind('keydown', 'Ctrl+a', function assets() {
			window.location.href = BASE_URL + '/administrator/Barang/add';
			return false;
		});

		$('*').bind('keydown', 'Ctrl+f', function assets() {
			$('#sbtn').trigger('click');
			return false;
		});

		$('*').bind('keydown', 'Ctrl+x', function assets() {
			$('#reset').trigger('click');
			return false;
		});

		$('*').bind('keydown', 'Ctrl+b', function assets() {

			$('#reset').trigger('click');
			return false;
		});
	}

	jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		<?= cclang('Stok Posko') ?><small><?= cclang('list_all'); ?></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active"><?= cclang('Stok Posko') ?></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body">
					<div class="box box-widget widget-user-2">
						<div class="widget-user-header">
							<div class="widget-user-image">
								<img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
							</div>
							<h3 class="widget-user-username"><?= cclang('Stok Posko') ?></h3>
							<h5 class="widget-user-desc"><?= cclang('list_all', [cclang('Stok Posko')]); ?> <i class="label bg-yellow"><?= $barang_counts; ?> <?= cclang('items'); ?></i></h5>
						</div>

						<div class="padd-left-0 ">
							<select class="form-control chosen chosen-select" name="posko" id="posko">
								<option value="">Pilih Posko</option>
								<?php foreach (db_get_all_data('posko') as $row): ?>
								<option value="<?= $row->posko_id ?>"><?= $row->posko_nama; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
					</div>
					<div class="table-responsive" id="result"></div>
				</div>
				<!--/box body -->
			</div>
			<!--/box -->
		</div>
	</div>
</section>
<!-- /.content -->

<!-- Page script -->

<script>
	$(document).ready(function () {
		$('#posko').change(function () {
			var idposko = $(this).val();

			$.ajax({
				url: "<?php echo site_url('administrator/barangposko/getdata');?>",
				method: "GET",
				data: {
					id: idposko
				},
				dataType: 'html',
				success: function (responses, data) {
					$('#result').html(responses);
				}
			});
			return false;
		});
	}); /*end doc ready*/
</script>